version: "1"
rules:
  - base: master
    upstream: apache:master
    mergeMethod: hardreset
  - base: d
    upstream: master
    assignees:
      - dorayx
    reviewers:
      - dorayx
label: ":arrow_heading_down: sync"